# Generated by Django 3.2.7 on 2023-02-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='session',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
